export const PLAYER_MOVE = "PLAYER_MOVE";
export const PLAYER_STOP = "PLAYER_STOP";
export const PLAYER_JOINED = "PLAYER_JOINED";

export const BROADCAST_PLAYER_JOINED = "BROADCAST_PLAYER_JOINED";
export const BROADCAST_PLAYER_POSITION = "BROADCAST_PLAYER_POSITION";
