export const PLAYER_MOVEMENT = "PLAYER_MOVEMENT";
export const PLAYER_JOINED = "PLAYER_JOINED";

export const AIRDROP_INIT = "AIRDROP_INIT";
export const AIRDROP_ANNOUNCE = "AIRDROP_ANNOUNCE";
export const AIRDROP_START = "AIRDROP_START";
export const AIRDROP_COINDROP = "AIRDROP_COINDROP";
export const AIRDROP_END = "AIRDROP_END";
export const AIRDROP_COINSPAWN = "AIRDROP_COINSPAWN";
export const AIRDROP_INVITE = "AIRDROP_INVITE";
export const AIRDROP_CONFIRM = "AIRDROP_CONFIRM";
export const AIRDROP_PLAYER_JOIN = "AIRDROP_PLAYER_JOIN";
